apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-nhcs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-nhcs
    app.kubernetes.io/part-of: load-app-514ed6fb-20e4-44e5-8985-e0abe2355469
  name: devfile-sample-go-basic-nhcs
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: devfile-sample-go-basic-nhcs
status:
  loadBalancer: {}
